"""All comparator settings (DESIGN.md section 18)."""

from pathlib import Path

_ROOT = Path(__file__).resolve().parent

INPUT_FOLDER = _ROOT / "INPUT"
OUTPUT_FOLDER = _ROOT / "OUTPUT"
TEMP_FOLDER = _ROOT / "OUTPUT" / "_tmp"

DS_SUFFIX = "_ds.csv"
INFA_SUFFIX = "_infa.csv"

MEMORY_LIMIT_MAX_GB = 2
MEMORY_LIMIT_MIN_GB = 1
MEMORY_SHARE_OF_AVAILABLE = 0.5
THREADS = None  # None → min(4, CPU cores)

READ_CHUNK_MB = 16
SNIFF_SAMPLE_ROWS = 20480
FORMAT_OVERRIDES: dict = {}

MAX_LINE_SIZE_BYTES = 2097152
REJECT_LIMIT_PERCENT = 1.0

KEY_MODE = "auto"  # "auto" or "none"
KEY_OVERRIDES: dict = {}
KEY_MIN_OVERLAP = 0.80
KEY_MAX_COLUMNS = 3
KEY_CANDIDATE_LIMIT = 5
KEY_NAME_HINTS = ["ID", "KEY", "NO", "NUM", "CODE"]

EXAMPLE_VALUES = 3
EXCEL_SAMPLE_ROWS = 100000
EXCEL_QUOTE_VALUES = True
FETCH_BATCH_ROWS = 10000

DISK_FREE_FACTOR = 4
KEEP_TEMP_ON_ERROR = False
